var allLocations = {
    guangzhou:{
        name:"广州",
        children:{
            yuexiu:{
                name:"越秀区",
            },
            tianhe:{
                name:"天河区"
            },
            haizhu:{
                name:"海珠区"
            }
        }
    },
    shenzhen:{
        name:"深圳",
        children:{
            baoan:{
              name:"宝安区",
            },
            luohu:{
              name:"罗湖区"
            },
            futian:{
              name:"福田区"
            },
            longhua:{
             name:"龙华区"
            }

        }
    },
    shanghai:{
        name:"上海"
    }
};


var allStores = {
    haizhu:[
        {
            identifier:"zhujiangxincheng",
            name:"珠江新城分店",
            status:"1",
            latitude:"23.125868",
            longitude:"113.328974",
            store_address:"珠江新城分店888号"
        },
        {
            identifier:"changlong",
            name:"长隆",
            status:"1",
            latitude:"23.008296",
            longitude:"113.332136",
            store_address:"长隆分店888号"
        }
    ],
    longhua:[
        {
            identifier:"shenzhennorth",
            name:"深圳北",
            status:"1",
            latitude:"22.615731",
            longitude:"114.035617",
            store_address:"深圳北分店888号"
        }
    ],
    futian:[
        {
            identifier:"chengongmiao",
            name:"车公庙",
            status:"1",
            latitude:"22.542382",
            longitude:"114.031736",
            store_address:"车公庙分店888号"
        },
        {
            identifier:"cocopark",
            name:"cocopark分店",
            status:"1",
            latitude:"22.540513",
            longitude:"114.059835",
            store_address:"cocopark分店888号"
        },
        {
            identifier:"close",
            name:"close莲花山分店",
            status:"0",
            latitude:"22.559538",
            longitude:"114.065009",
            store_address:"close莲花山分店888号"
        },
    ]
};